### ISSUE TITLE
unable to upload images since last update

### ISSUE THREAD

**Issue by ballinger** [YunoHost-Apps/tandoor_ynh#89]
- Hardware: vps
- YunoHost version: 12.0.6
- I have access to my server: SSH, webadmin

image upload is denied since last update (1.5.19~ynh2). android app untare still has issues displaying images - image api denied flashes up.

**Comment by ballinger** [comment]
same for 5.20 from testing

**Comment by ballinger** [comment]
discovered that the android app untar is discontinued. [kitchn](https://github.com/aimok04/kitshn) is under active development, but has the same problem fetching the media / images from tandoor. ynh related?

**Comment by ballinger** [comment]
something in the update process that breaks image upload. exported recepies, removed the app, reinstall, import and all is working again. no idea, only suspicious thing i saw where mixed user rights inside the media dir. most of them tandoor:www-data, some tandoor:tandoor. i am on 1.5.22 now

**Comment by mc-knife** [comment]
same problem here (started with app version 1.5.19, continued after deb11->12 and app upgrade to 1.5.22~ynh1)

**Comment by mc-knife** [comment]
concerning your workaround:
> exported recepies, removed the app, reinstall, import and all is working again.

did you have to manually re-setup your space bevor importing recepies? what about keywords, foods, units? i do not see them in the export. didn't you lose everything removing the app?

i cannot find any other export/backup feature than just the recepies.

**Comment by mc-knife** [comment]
this is the forum with the same error and more insight into log-file:
https://forum.yunohost.org/t/error-with-tandoor-image-update/30969

**Comment by ballinger** [comment]
Hmm, ok. Yes I would have lost everything. I just started out on tandoor, coming from nextcloud cookbook with exported recipes.
Same behavior for latest 23 update.

**Comment by NiklasMM** [comment]
I've tried to get this app to run again, but given up since for two reasons. 

1. Using a different python version than whatever is the one that comes with Debian in Yunohost is not easy to do. There seems to be no standard way to do it. 

2. Tandoor just isn't a very well maintained app as it is. It doesn't follow standard practices for Python apps. They don't even explicitly define which versions they support and seem to change them willy nilly. 

I've since moved to [Mealie](https://docs.mealie.io/) which I deployed using docker compose alongside yunohost.

**Comment by ballinger** [comment]
i was hoping to get mealie into a propper ynh pkg but failed miserably. tandoor just feels and is unmaintained. i see one guy tinkering around... quite a contrast to mealies changelog. anyways.. that update thing with tandoor atm, that i got no images in the android app makes me ask.... 

- rough guidlines on how to set up mealie, docker without braking ynh? i have a docker playground on a pi here, got mealie up and running on a vanilla debian install.
- can i use my food domain from ynh in the composer file and let ynh do the letsencrypt domain stuff?

**Comment by NiklasMM** [comment]
Yeah sure, you can install docker on a yunohost. Just [follow the instructions](https://docs.docker.com/engine/install/debian/). It won't break anything as ynh doesn't use docker anyway. Then follow the instructions to deploy via docker in the mealie docs.

I recommend using the [reverse proxy](https://github.com/YunoHost-Apps/reverseproxy_ynh) ynh package to tie mealie into ynh. That way you'll be able to manage domain and tls-cert stuff via ynh.

I've not yet managed to connect mealie to the ynh ldap for time reasons, but it should be possible. 

Feel free to contact me via any of the means listed on my profile if you need further assistance.

**Comment by mc-knife** [comment]
just for the log: latest version 1.5.24~ynh1: still the same behavior.

**Comment by mc-knife** [comment]
i can see the same, concerning rights and ownership.
BUT:
> They are all uploaded 100% and are correctly stored in this folder.
i am not shure, if the images are stored "correctly". as they are not named in the same convention than older uploads from times when everything was working.

so my impression is: images are indeed uploaded. but not processed by tandoor to be integrated (renamed and linked to the recepie). and that makes totally sense to me in connection with the information, that python 3.12 is needed (as mentioned [above](https://github.com/YunoHost-Apps/tandoor_ynh/issues/89#issuecomment-2481750603)) 

ergo: upload is ok, but processing is broken because of wrong python version.

**Comment by DrOuille9** [comment]
> i am not shure, if the images are stored "correctly". as they are not named in the same convention than older uploads from times when everything was working.
"Correctly" as the file is not corrupted and fully readable ;)

**Comment by mc-knife** [comment]
i think waiting for upcoming tandoor versions won't help, since it is not a tandoor problem but an issue with the environment tandoor is installed in. it is rather a yunohost packaging issue.
since this ist the tandoor_ynh repo: has anybody an idea how to change/upgrade the python version shipping with the yunohost-tandoor-package?

**Comment by mc-knife** [comment]
> it is rather a yunohost packaging issue.

no it isn't. reading docs and learning, i believe it is about 

1. installing an alternative python version into bookworm with `make altinstall`
see: https://wiki.debian.org/Python#Installing_from_Source 
2. linking that python version to ynh-tandoor
edit `/var/www/tandoor/venv/pyvenv.cfg`

didn't dare to try it yet. but how does this sound - technically, apart from basic arguments pro and contra "frankensteinization" of the underlying debian version?

**Comment by NiklasMM** [comment]
I already tried manually installing Python 3.12 and running tandoor with it. It yielded the same error with image uploads. So I assume there's something wrong with the way the app is set up. I asked [upstream](https://github.com/TandoorRecipes/recipes/issues/3318), but they won't help with "manual" setups.

I moved on from tandoor, but thought I'd let you know updating to 3.12 won't fix it.

**Comment by mc-knife** [comment]
> I've since moved to [Mealie](https://docs.mealie.io/) which I deployed using docker compose alongside yunohost.

please allow a slightly off-topic question: how as export-import from tandoor to mealie? did you have to do a lot of manual post-migration work on your recepies to have them beautifully in mealie?

**Comment by ballinger** [comment]
Tandoor to mealie via zip -> fine
Mealie to tandoor via zip -> fine
Mealie 1.3 to mealie 2.3 -> ugh... Eventually worked by exporting every recipe in its own zip then import is fine

Do users who came here for mealie / docker yeh setup,
https://github.com/YunoHost-Apps/tandoor_ynh/issues/89#issuecomment-2500866049
Instead of reverse proxy use the redirect app!

**Comment by DrOuille9** [comment]
Hey!

Current release is 1.5.25~ynh1
A test :
Import recipe from a website. The text is ok, but add an error message popup (can't remember, too fast).
Image is not displaying as before...
But, I see it stored in `/var/www/tandoor/mediafiles/recipes` with a name like older working images (cd924a7e-e6ba-4006-8851-5fd39473c3a1_11.jpg), may be the main difference I see, and about file rights : `-rw-r--r--` `tandoor:tandoor`

Thx for this update. May be Python will not be the main problem to this soft ?

**Comment by GrosMatou27** [comment]
Hello. I have the same problem. Maybe some information than can help :
New install from 2 weeks ago (1.5.24) the images upload was working. On Monday, I added a new space and new user, and try to update from 1.5.24 to 1.5.27 but failed. So I restore the pre-update backup with 1.5.24. 
Now the image update is not working anymore, but can't say if the reason is the new space/user or the failed backup/restore

**Comment by mc-knife** [comment]
> New install from 2 weeks ago (1.5.24) the images upload was working.

that is interesting. after restoring your backup: did you try to delete your new user(s)/space? (just to narrow the possibilities.)

**Comment by R-0ne** [comment]
Same problem here... everything was working fine until I added a new user to the group, since then it's been impossible to upload an image???

**Comment by ndx1905-github** [comment]
Same happened here while updating from 1.5.33 to 1.5.34~ynh1

Before update I could upload images. Now I can't 

When I look at the media files directory I see that pictures uploaded before are in the form of c8e0e843-760e-4757-8df6-2d3e5f2c0e99_18.jpg
whereas now when I try to upload an app it gets written to the same directory, but keeps its original upload name and file permissions are different.
First images belong to user tandoor from the www-data group
New images that are failed belong to user tandoor from the tandoor group

**Comment by Thovi98** [comment]
I've made some changes in the scripts in latest version. Could someone check?

**Comment by mc-knife** [comment]
@Thovi98 : thanks a lot for working on a fix! 

> Hi, I updated my server and image upload is working fine...thanks a lot!

@R-0ne : thanks for testing!

just to make shure before testing the update: which version are you running now that is working for you? 
(latest version for me to update to right now according to yunohost gui update procedure is version 2.0.1~ynh1.)

right now i am running the so far last working version 1.5.25~ynh1.
which version did you update from?
are there any concerns updating from 1.5.25 -> 2.0.1 ?

**Comment by mc-knife** [comment]
I dared to update my tandoor, too. from 1.5.25 to 2.0.1 and I can confirm: Image upload is working fine.
Thanks a lot from me too!!

**Comment by Thovi98** [comment]
Thanks for your feedback!
So it was not a python issue (nothing has changes about it), but rather a permission issue.
Enjoy the app!

**Comment by DrOuille9** [comment]
Working like a charm !
Thx mister ! 🥇
